#!/usr/bin/env python
"""
Copyright 2014-2015 Taxamo, Ltd.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class By_taxation_type:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'taxed_count': 'number',
            'deducted_count': 'number',
            'transactions_count': 'number',
            'eu_b2b': 'integer',
            'eu_taxed': 'integer'

        }


        #Number of taxed transactions.
        self.taxed_count = None # number
        #Number of tax deducted transactions.
        self.deducted_count = None # number
        #Total number of transactions
        self.transactions_count = None # number
        #Total EU B2B transaction count.
        self.eu_b2b = None # integer
        #Total EU Taxed transaction count.
        self.eu_taxed = None # integer
        
