#!/usr/bin/env python
"""
Copyright 2014 Taxamo, Ltd.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class CreateRefundIn:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'line_key': 'str',
            'custom_id': 'str',
            'amount': 'number',
            'total_amount': 'number'

        }


        #Line identifier. Either line key or custom id is required.
        self.line_key = None # str
        #Line custom identifier. Either line key or custom id is required.
        self.custom_id = None # str
        #Amount (without tax) to be refunded. Either amount or total amount is required.
        self.amount = None # number
        #Total amount, including tax, to be refunded. Either amount or total amount is required.
        self.total_amount = None # number
        
