#!/usr/bin/env python
"""
Copyright 2014-2015 Taxamo, Ltd.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class CreateRefundOut:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'total_amount': 'number',
            'tax_amount': 'number',
            'refunded_total_amount': 'number',
            'refunded_tax_amount': 'number'

        }


        #Total amount, including tax, that was refunded in this call.
        self.total_amount = None # number
        #Calculated tax amount, that was refunded in this call.
        self.tax_amount = None # number
        #Total amount, including tax, that was refunded for this line.
        self.refunded_total_amount = None # number
        #Total tax amount, that was refunded for this line.
        self.refunded_tax_amount = None # number
        
