#!/usr/bin/env python
"""
Copyright 2014-2015 Taxamo, Ltd.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Currency_schema:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'code': 'str',
            'minorunits': 'integer',
            'description': 'str',
            'isocode': 'str',
            'isonum': 'integer'

        }


        #Currency 3-letter ISO code.
        self.code = None # str
        #Number of minor units for currency.
        self.minorunits = None # integer
        #Currency description.
        self.description = None # str
        #Currency 3-letter ISO code.
        self.isocode = None # str
        #Currency iso numeric code.
        self.isonum = None # integer
        
