#!/usr/bin/env python
"""
Copyright 2014 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Input_transaction_line:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'custom_id': 'str',
            'product_type': 'str',
            'quantity': 'number',
            'unit_price': 'number',
            'unit_of_measure': 'str',
            'total_amount': 'number',
            'line_key': 'str',
            'amount': 'number',
            'description': 'str',
            'product_code': 'str',
            'supply_date': 'str'

        }


        #Custom id, provided by ecommerce software.
        self.custom_id = None # str
        #Product type, according to dictionary /dictionaries/product_types
        self.product_type = None # str
        #Quantity Defaults to 1.
        self.quantity = None # number
        #Unit price.
        self.unit_price = None # number
        #Unit of measure.
        self.unit_of_measure = None # str
        #Total amount. Required if amount is not provided.
        self.total_amount = None # number
        #Generated line key.
        self.line_key = None # str
        #Amount. Required if total amount is not provided.
        self.amount = None # number
        #Line contents description.
        self.description = None # str
        #Internal product code, used for invoicing for example.
        self.product_code = None # str
        #Date of supply in yyyy-MM-dd format.
        self.supply_date = None # str
        
