#!/usr/bin/env python
"""
Copyright 2014-2015 Taxamo, Ltd.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Invoice_address:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'freeform_address': 'str',
            'building_number': 'str',
            'street_name': 'str',
            'address_detail': 'str',
            'city': 'str',
            'postal_code': 'str',
            'region': 'str',
            'country': 'str'

        }


        #Freeform address. Use when structured data is not available. Will be used in SAF-MOSS file if other fields are not provided.
        self.freeform_address = None # str
        #Building number.
        self.building_number = None # str
        # Street name.
        self.street_name = None # str
        #Address details - for example apartament number.
        self.address_detail = None # str
        #City name.
        self.city = None # str
        #Postal code.
        self.postal_code = None # str
        #Region, for United States - state code - e.g. NJ.
        self.region = None # str
        #2-letter ISO country code.
        self.country = None # str
        
