#!/usr/bin/env python
"""
Copyright 2014-2015 Taxamo, Ltd.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Refunds:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'refund_note_url': 'str',
            'refund_note_number': 'str',
            'line_key': 'str',
            'refund_timestamp': 'str',
            'amount': 'number',
            'informative': 'bool',
            'tax_amount': 'number',
            'tax_rate': 'number',
            'total_amount': 'number',
            'refund_reason': 'str'

        }


        #Refund note image url.
        self.refund_note_url = None # str
        #Sequential refund note number.
        self.refund_note_number = None # str
        #Line identifier. If neither line key or custom id is provided, the refund amount will be assigned to lines in order.
        self.line_key = None # str
        #Refund timestamp in UTC timezone.
        self.refund_timestamp = None # str
        #Amount, excluding tax, that was refunded.
        self.amount = None # number
        #Was this refund applied to an informative line?
        self.informative = None # bool
        #Calculated tax amount, that was refunded.
        self.tax_amount = None # number
        #Tax rate for the line that was used for the refund calculation.
        self.tax_rate = None # number
        #Total amount, including tax, that was refunded.
        self.total_amount = None # number
        #Refund reason, displayed on the credit note.
        self.refund_reason = None # str
        
