#!/usr/bin/env python
"""
Copyright 2014-2015 Taxamo, Ltd.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Settlement_daily_stats_schema:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'b2c': 'integer',
            'untaxed': 'integer',
            'eu_taxed': 'integer',
            'eu_b2b': 'integer',
            'count': 'integer',
            'eu_total': 'integer',
            'day_raw': 'str',
            'b2b': 'integer',
            'day': 'str'

        }


        #B2C transaction count.
        self.b2c = None # integer
        #Untaxed transaction count.
        self.untaxed = None # integer
        #Total EU Taxed transaction count.
        self.eu_taxed = None # integer
        #Total EU B2B transaction count.
        self.eu_b2b = None # integer
        #Total transaction count.
        self.count = None # integer
        #Total EU transaction count.
        self.eu_total = None # integer
        #Date for stats in yyyy-MM-dd'T'hh:mm:ss'Z' format.
        self.day_raw = None # str
        #B2B transaction count.
        self.b2b = None # integer
        #Date for stats in yyyy-MM-dd format.
        self.day = None # str
        
