#!/usr/bin/env python
"""
Copyright 2014-2021 by Taxamo

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Ship_to_address:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'used_for_tax_calculation': 'bool',
            'city': 'str',
            'postal_code': 'str',
            'county': 'str',
            'country_code': 'str',
            'street_name': 'str',
            'region': 'str',
            'address_detail': 'str',
            'freeform_address': 'str',
            'building_number': 'str'

        }


        #If the address has been used for tax calculation (digital only).
        self.used_for_tax_calculation = None # bool
        #City name.
        self.city = None # str
        #Postal code.
        self.postal_code = None # str
        #County name
        self.county = None # str
        #Two-letter ISO country code, e.g. FR.
        self.country_code = None # str
        # Street name.
        self.street_name = None # str
        #Region, for United States - state code - e.g. NJ.
        self.region = None # str
        #Address details - for example apartament number.
        self.address_detail = None # str
        #Freeform address. Use when structured data is not available. Will be used in SAF-MOSS file if other fields are not provided.
        self.freeform_address = None # str
        #Building number.
        self.building_number = None # str
        
